### ISSUE TITLE
2 Feedback

### ISSUE THREAD

**Issue by berat** [omergulen/producthunt-trending-extension#6]
- [ ] A different color can be made when it comes to the voting section to make it more interactive.
- [ ] The random icon can be placed next to the title.

If you say "okay, let's do it" I can do it

**Comment by omergulen** [comment]
@berat I think more interactive voting section is not a good idea, because there is button or something. User can't do any actions with voting section, so making it look more interactive is not the thing we should do.

And I didn't get the second feedback you suggested, what you mean by random icon, why?

**Comment by berat** [comment]
The random icon is right next to the box. Maybe if we take it by the hood, we can make it appear. Because I didn't see it the first time.
